# Generated by Django 5.1.6 on 2025-03-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
