# Generated by Django 5.1.6 on 2025-03-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
