# Generated by Django 5.1.6 on 2025-03-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Used'), (3, 'Unpacked')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'SOLD')], default=1),
        ),
    ]
