# Generated by Django 5.1.6 on 2025-04-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_contactdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
