# Generated by Django 5.1.6 on 2025-04-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0007_region_country_id'),
        ('product', '0014_product_brand_product_category_product_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorys.region')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_n', models.CharField(max_length=300)),
                ('enter_address', models.TextField()),
                ('city_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.area')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.country')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorys.region')),
            ],
        ),
    ]
