# Generated by Django 5.1.6 on 2025-04-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_area_contactdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='city_area',
            field=models.ForeignKey(default='Toshkent', on_delete=django.db.models.deletion.CASCADE, to='product.area'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
