# Generated by Django 5.1.6 on 2025-04-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_contactdetail_city_area_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
