# Generated by Django 5.1.6 on 2025-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_optional', models.BooleanField(default=False)),
                ('for_footer', models.BooleanField(default=False)),
                ('for_mid_part', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
