# Generated by Django 5.1.6 on 2025-03-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorys.categorys'),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorys/'),
        ),
    ]
