# Generated by Django 5.1.6 on 2025-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_categorys_parent_alter_categorys_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='for_header',
            field=models.BooleanField(default=False),
        ),
    ]
