# Generated by Django 5.1.6 on 2025-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0003_categorys_for_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
