# Generated by Django 5.1.6 on 2025-03-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0004_alter_categorys_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorys',
            old_name='is_optional',
            new_name='is_option',
        ),
    ]
